package_name: vala
version: 0.1.0
license: GPLv2+
summary: Vala assistants (console app, Gtk)
homepage: https://github.com/ilent2/dap-vala
authors: [Isaac Lenton <isaac@isuniversal.com>]
bugreports: https://github.com/ilent2/dap-vala/issues
description: Set of crt assistants for Vala.  Contains assistants for new console program and Gtk application.
